spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advanced_pharmacy_db
    username: postgres
    password: 12345

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    phone: ${ADMIN_PHONE}
    password: ${ADMIN_PASSWORD}

file:
  prescription:
    max-size: 5MB
    allowed-types:
      - application/pdf
      - image/jpeg


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}